services:
  watchtower:
    image: containrrr/watchtower:latest
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json # Auth for private registry

  next:
    image: ghcr.io/laurimaila/personal-website:latest
    ports:
      - "3500:3000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - NODE_ENV=production
    restart: always
    platform: linux/arm64

  backend:
    image: ghcr.io/laurimaila/backend-personal-website:latest
    ports:
      - "3600:80"
    depends_on:
      - db
      - liquibase
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      CONNECTION_STRING: Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

  db:
    image: postgres:17-alpine
    restart: always
    volumes: # Store data in a docker volume
      - db-prod:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  liquibase: # Run db migrations with Liquibase
    container_name: liquibase
    image: liquibase/liquibase:4.28
    volumes:
      - ./database/liquibase/changelog/:/liquibase/changelog/
    command: --defaults-file=/liquibase/changelog/liquibase.properties --url=jdbc:postgresql://db:5432/${POSTGRES_DB} --username=${POSTGRES_USER} --password=${POSTGRES_PASSWORD} update
    depends_on:
      - db

volumes:
  db-prod:
