FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

COPY ./backend.csproj ./
RUN dotnet restore

COPY . ./

EXPOSE 3000

ENV ASPNETCORE_URLS=http://+:3000

ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:3000"]
