// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: physics.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PhysicsService_GenerateLorenz_FullMethodName = "/PhysicsService.PhysicsService/GenerateLorenz"
)

// PhysicsServiceClient is the client API for PhysicsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhysicsServiceClient interface {
	GenerateLorenz(ctx context.Context, in *LorenzRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LorenzResponse], error)
}

type physicsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPhysicsServiceClient(cc grpc.ClientConnInterface) PhysicsServiceClient {
	return &physicsServiceClient{cc}
}

func (c *physicsServiceClient) GenerateLorenz(ctx context.Context, in *LorenzRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LorenzResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PhysicsService_ServiceDesc.Streams[0], PhysicsService_GenerateLorenz_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LorenzRequest, LorenzResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PhysicsService_GenerateLorenzClient = grpc.ServerStreamingClient[LorenzResponse]

// PhysicsServiceServer is the server API for PhysicsService service.
// All implementations must embed UnimplementedPhysicsServiceServer
// for forward compatibility.
type PhysicsServiceServer interface {
	GenerateLorenz(*LorenzRequest, grpc.ServerStreamingServer[LorenzResponse]) error
	mustEmbedUnimplementedPhysicsServiceServer()
}

// UnimplementedPhysicsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPhysicsServiceServer struct{}

func (UnimplementedPhysicsServiceServer) GenerateLorenz(*LorenzRequest, grpc.ServerStreamingServer[LorenzResponse]) error {
	return status.Error(codes.Unimplemented, "method GenerateLorenz not implemented")
}
func (UnimplementedPhysicsServiceServer) mustEmbedUnimplementedPhysicsServiceServer() {}
func (UnimplementedPhysicsServiceServer) testEmbeddedByValue()                        {}

// UnsafePhysicsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhysicsServiceServer will
// result in compilation errors.
type UnsafePhysicsServiceServer interface {
	mustEmbedUnimplementedPhysicsServiceServer()
}

func RegisterPhysicsServiceServer(s grpc.ServiceRegistrar, srv PhysicsServiceServer) {
	// If the following call panics, it indicates UnimplementedPhysicsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PhysicsService_ServiceDesc, srv)
}

func _PhysicsService_GenerateLorenz_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LorenzRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PhysicsServiceServer).GenerateLorenz(m, &grpc.GenericServerStream[LorenzRequest, LorenzResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PhysicsService_GenerateLorenzServer = grpc.ServerStreamingServer[LorenzResponse]

// PhysicsService_ServiceDesc is the grpc.ServiceDesc for PhysicsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhysicsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PhysicsService.PhysicsService",
	HandlerType: (*PhysicsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateLorenz",
			Handler:       _PhysicsService_GenerateLorenz_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "physics.proto",
}
