// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: physics.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LorenzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sigma         float64                `protobuf:"fixed64,1,opt,name=sigma,proto3" json:"sigma,omitempty"`
	Rho           float64                `protobuf:"fixed64,2,opt,name=rho,proto3" json:"rho,omitempty"`
	Beta          float64                `protobuf:"fixed64,3,opt,name=beta,proto3" json:"beta,omitempty"`
	Dt            float64                `protobuf:"fixed64,4,opt,name=dt,proto3" json:"dt,omitempty"`
	MaxIterations int32                  `protobuf:"varint,5,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LorenzRequest) Reset() {
	*x = LorenzRequest{}
	mi := &file_physics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LorenzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LorenzRequest) ProtoMessage() {}

func (x *LorenzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_physics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LorenzRequest.ProtoReflect.Descriptor instead.
func (*LorenzRequest) Descriptor() ([]byte, []int) {
	return file_physics_proto_rawDescGZIP(), []int{0}
}

func (x *LorenzRequest) GetSigma() float64 {
	if x != nil {
		return x.Sigma
	}
	return 0
}

func (x *LorenzRequest) GetRho() float64 {
	if x != nil {
		return x.Rho
	}
	return 0
}

func (x *LorenzRequest) GetBeta() float64 {
	if x != nil {
		return x.Beta
	}
	return 0
}

func (x *LorenzRequest) GetDt() float64 {
	if x != nil {
		return x.Dt
	}
	return 0
}

func (x *LorenzRequest) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

type LorenzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LorenzResponse) Reset() {
	*x = LorenzResponse{}
	mi := &file_physics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LorenzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LorenzResponse) ProtoMessage() {}

func (x *LorenzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_physics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LorenzResponse.ProtoReflect.Descriptor instead.
func (*LorenzResponse) Descriptor() ([]byte, []int) {
	return file_physics_proto_rawDescGZIP(), []int{1}
}

func (x *LorenzResponse) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *LorenzResponse) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *LorenzResponse) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_physics_proto protoreflect.FileDescriptor

const file_physics_proto_rawDesc = "" +
	"\n" +
	"\rphysics.proto\x12\x0ePhysicsService\"\x82\x01\n" +
	"\rLorenzRequest\x12\x14\n" +
	"\x05sigma\x18\x01 \x01(\x01R\x05sigma\x12\x10\n" +
	"\x03rho\x18\x02 \x01(\x01R\x03rho\x12\x12\n" +
	"\x04beta\x18\x03 \x01(\x01R\x04beta\x12\x0e\n" +
	"\x02dt\x18\x04 \x01(\x01R\x02dt\x12%\n" +
	"\x0emax_iterations\x18\x05 \x01(\x05R\rmaxIterations\":\n" +
	"\x0eLorenzResponse\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z2c\n" +
	"\x0ePhysicsService\x12Q\n" +
	"\x0eGenerateLorenz\x12\x1d.PhysicsService.LorenzRequest\x1a\x1e.PhysicsService.LorenzResponse0\x01B\x17Z\x04./pb\xaa\x02\x0eBackend.Protosb\x06proto3"

var (
	file_physics_proto_rawDescOnce sync.Once
	file_physics_proto_rawDescData []byte
)

func file_physics_proto_rawDescGZIP() []byte {
	file_physics_proto_rawDescOnce.Do(func() {
		file_physics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_physics_proto_rawDesc), len(file_physics_proto_rawDesc)))
	})
	return file_physics_proto_rawDescData
}

var file_physics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_physics_proto_goTypes = []any{
	(*LorenzRequest)(nil),  // 0: PhysicsService.LorenzRequest
	(*LorenzResponse)(nil), // 1: PhysicsService.LorenzResponse
}
var file_physics_proto_depIdxs = []int32{
	0, // 0: PhysicsService.PhysicsService.GenerateLorenz:input_type -> PhysicsService.LorenzRequest
	1, // 1: PhysicsService.PhysicsService.GenerateLorenz:output_type -> PhysicsService.LorenzResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_physics_proto_init() }
func file_physics_proto_init() {
	if File_physics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_physics_proto_rawDesc), len(file_physics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_physics_proto_goTypes,
		DependencyIndexes: file_physics_proto_depIdxs,
		MessageInfos:      file_physics_proto_msgTypes,
	}.Build()
	File_physics_proto = out.File
	file_physics_proto_goTypes = nil
	file_physics_proto_depIdxs = nil
}
