name: Lint and test backend

on:
  workflow_call:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10

      - name: Lint
        run: dotnet format --verify-no-changes --verbosity diagnostic backend.slnx

      - name: Run tests
        run: dotnet test backend.slnx
